Let C++ create and own the QMLBridge instance
It's a global singleton type, doesn't make sense to let QML manage it.
Before this change, it was destroyed too early, causing warnings on exit like:

TypeError: Cannot read property 'myData' of null